name: CI

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout le code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Installer Yarn 4.x
        run: |
          corepack enable
          yarn set version stable
          yarn --version

      - name: Installer les dépendances
        run: yarn install --immutable

      - name: Linter
        run: yarn lint

      - name: Tests unitaires
        run: yarn test

      - name: Retire
        run: yarn retire

      - name: Audit deps
        run: yarn npm audit -R --environment production

      - name: Connexion à GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Extraire la version du package.json
        id: pkg
        run: echo "version=$(jq -r .version package.json)" >> "$GITHUB_OUTPUT"

      - name: Préparer le nom de l'image (en minuscules)
        id: image
        run: |
          owner_lc=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          echo "name=ghcr.io/$owner_lc/backend-node" >> "$GITHUB_OUTPUT"

      - name: Build et push image Docker
        run: |
          docker build -t ${{ steps.image.outputs.name }}:latest .
          docker push ${{ steps.image.outputs.name }}:latest
